services:
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
        container_name: kavita
        volumes:
            - M:\manga\:/manga
            - M:\comics\:/comics
            - M:\ebooks\:/books
            - C:\docker\kavita\:/kavita/config     # /kavita/config must not be changed
        environment:
            - TZ=America/New_York
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        ports:
            - "5000:5000"
        restart: unless-stopped
