---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Plex:
        href: "http://192.168.0.17:32400"
        description: Media Library
        icon: plex.png
        widget:
          type: plex
          url: http://192.168.0.17:32400
          key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Tautulli:
        href: "http://192.168.0.17:8181"
        description: Media Server Monitoring
        icon: tautulli.png
        widget:
          type: tautulli
          url: http://192.168.0.17:8181
          key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: true # optional, defaults to true
    - Kavita:
        href: "http://192.168.0.17:5000"
        description: eBook Library
        icon: kavita.png
        widget:
          type: kavita
          url: "http://192.168.0.17:5000"
          username: {{HOMEPAGE_VAR_KAVITA_USERNAME}}
          password: {{HOMEPAGE_VAR_KAVITA_PASSWORD}}
    - AudioBookShelf:
        href: "http://192.168.0.17:13378"
        description: Audiobook Library
        icon: audiobookshelf.png
        widget:
          type: audiobookshelf
          url: "http://192.168.0.17:13378/"
          key: {{HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}}
        

- Containers and Services:
    - Portainer hmmpi1:
        href: https://192.168.0.5:9443
        description: Used for home services
        icon: portainer.png
        widget:
          type: portainer
          url: https://192.168.0.5:9443
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Portainer MediaPC:
        href: https://192.168.0.5:9443
        description: MediaPC Environment
        icon: portainer.png
        widget:
          type: portainer
          url: https://192.168.0.5:9443
          env: 4
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Minecraft Server:
        icon: minecraft.png
        widget:
          type: minecraft
          url: udp://192.168.0.17:25565
    - Plane:
        href: http://192.168.0.5:12800
        description: Scrum Management
        icon: plane.svg


- Networking:
    - Router:
        href: http://192.168.0.1
        description: TP-Link AX-5400
        icon: tp-link.png
