version: '2.4'
services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
     - ./:/octoprint
    environment:
     - ENABLE_MJPG_STREAMER=true
volumes:
  octoprint:
